### ISSUE TITLE
CryFS comparison

### ISSUE THREAD

**Issue by Kodiman** [rfjakob/gocryptfs-website#1]
Hi. Your gocryptfs is excellent. Please add CryFS to your comparison study. Thanks.
https://www.cryfs.org/

**Comment by rfjakob** [comment]
Yes, we should really have CryFS as well. Added: https://nuetzlich.net/gocryptfs/comparison/

**Comment by Tuxie** [comment]
Please also add a "file modification timestamp obfuscation" point to the comparison. AFAIK, currently only CryFS hides the original file timestamps.

This is not only valuable for hiding the timestamps but also because many cloud filesystems don't preserve the original timestamps of files when used directly.
